const renderPage = () => {
  const bodyElement = document.body;
  bodyElement.classList.add('d-flex', 'flex-column', 'min-vh-100');
  const pageMain = document.createElement('main');
  const jumbotron = document.createElement('div');
  const jumbotronContainer = document.createElement('div');
  const jumbotronRow = document.createElement('div');
  const jumbotronCol = document.createElement('div');
  const title1 = document.createElement('h1');
  const info = document.createElement('p');
  const formElement = document.createElement('form');
  const formRow = document.createElement('div');
  const formCol1 = document.createElement('div');
  const formCol2 = document.createElement('div');
  const fieldElement = document.createElement('input');
  const submitElement = document.createElement('button');
  const hint = document.createElement('p');
  const processInfo = document.createElement('p');
  const pageMainContainer = document.createElement('div');
  const pageMainRow = document.createElement('div');
  const pageMainCol = document.createElement('div');
  const pageFooter = document.createElement('footer');
  const pageFooterContainer = document.createElement('div');
  const pageFooterTextWrap = document.createElement('p');

  processInfo.classList.add('processInfo');
  hint.classList.add('text-muted', 'my-1');
  hint.setAttribute('data-hint', 'hint');
  fieldElement.type = 'text';
  fieldElement.classList.add('form-control', 'form-control-lg', 'w-100');
  fieldElement.name = 'url';
  fieldElement.setAttribute('required', '');
  submitElement.type = 'submit';
  submitElement.classList.add('btn', 'btn-lg', 'btn-primary', 'px-sm-5');
  submitElement.setAttribute('data-btn', 'submit-btn');
  formCol1.classList.add('col');
  formCol1.appendChild(fieldElement);
  formCol2.classList.add('col-auto');
  formCol2.appendChild(submitElement);
  formRow.classList.add('form-row');
  formRow.append(formCol1, formCol2);
  formElement.appendChild(formRow);
  formElement.setAttribute('data-form', 'rss-form');
  info.classList.add('lead');
  info.setAttribute('data-info', 'info');
  title1.classList.add('display-3');
  title1.setAttribute('data-title', 'main-title');
  jumbotronCol.classList.add('col-md-10', 'col-lg-8', 'mx-auto', 'text-white');
  jumbotronCol.append(title1, info, formElement, hint, processInfo);
  jumbotronRow.classList.add('row');
  jumbotronRow.appendChild(jumbotronCol);
  jumbotronContainer.classList.add('container');
  jumbotronContainer.appendChild(jumbotronRow);
  jumbotron.classList.add('jumbotron', 'jumbotron-fluid', 'bg-dark');
  jumbotron.appendChild(jumbotronContainer);
  pageMain.classList.add('flex-grow-1');
  pageMainCol.classList.add('col-md-10', 'col-lg-8', 'mx-auto', 'feeds');
  pageMainCol.setAttribute('data-container', 'content');
  pageMainRow.classList.add('row');
  pageMainRow.appendChild(pageMainCol);
  pageMainContainer.classList.add('container');
  pageMainContainer.appendChild(pageMainRow);
  pageMain.append(jumbotron, pageMainContainer);
  pageFooterTextWrap.classList.add('text-center');
  pageFooterContainer.classList.add('container');
  pageFooterTextWrap.setAttribute('data-copyright', 'by-hexlet');
  pageFooterContainer.appendChild(pageFooterTextWrap);
  pageFooter.appendChild(pageFooterContainer);
  pageFooter.classList.add('footer', 'border-top', 'py-3', 'mt-5');
  bodyElement.prepend(pageMain, pageFooter);
};

export default renderPage;
